#
#
#
CC=gcc
CFLAGS=-Wall


#all : longest_line
#.PHONY : all
#
#erTi faili
longest : longest_line.o
	$(CC) $(CFLAGS) -o udidesi longest_line.o

longest_line.o : longest_line.c
	$(CC) $(CFLAGS) -c -o longest_line.o longest_line.c
